AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - './spec/**/**'
    - './examples/**'

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 169

Metrics/MethodLength:
  Max: 14