module Resend
  VERSION: String

  def self.api_key: () -> String?
  def self.api_key=: (String api_key) -> String
  def self.configure: () { (Resend) -> void } -> bool
  alias config configure
end

require "resend/response"
require "resend/emails"
require "resend/emails/receiving"
require "resend/webhooks"
