module Resend
  module Emails
    type email_tag = { name: String, value: String }

    type email_last_event =
      | "bounced"
      | "canceled"
      | "clicked"
      | "complained"
      | "delivered"
      | "delivery_delayed"
      | "failed"
      | "opened"
      | "queued"
      | "scheduled"
      | "sent"
      | "suppressed"

    type get_email_response = {
      object: "email",
      id: String,
      message_id: String,
      to: Array[String],
      from: String,
      created_at: String,
      subject: String,
      html: String?,
      text: String?,
      bcc: Array[String]?,
      cc: Array[String]?,
      reply_to: Array[String]?,
      last_event: email_last_event,
      scheduled_at: String?,
      tags?: Array[email_tag],
      topic_id?: String?,
    }

    type list_email = {
      id: String,
      message_id: String,
      to: Array[String],
      from: String,
      created_at: String,
      subject: String,
      last_event: email_last_event,
      scheduled_at: String?,
      topic_id?: String?,
    }

    type list_emails_response = {
      object: "list",
      has_more: bool,
      data: Array[list_email],
    }

    def self.send: (Hash[Symbol, untyped] params, ?options: Hash[Symbol, untyped]) -> Resend::Response
    def self.get: (String email_id) -> (Resend::Response & get_email_response)
    def self.update: (Hash[Symbol, untyped] params) -> Resend::Response
    def self.cancel: (String email_id) -> Resend::Response
    def self.list: (?limit: Integer?, ?after: String?, ?before: String?) -> (Resend::Response & list_emails_response)
  end
end
