module Resend
  module Emails
    module Receiving
      type inbound_attachment = {
        id: String,
        filename: String?,
        size: Integer,
        content_type: String,
        content_id: String?,
        content_disposition: String?,
      }

      type get_receiving_email_response = {
        object: "email",
        id: String,
        to: Array[String],
        from: String,
        created_at: String,
        subject: String,
        bcc: Array[String]?,
        cc: Array[String]?,
        reply_to: Array[String]?,
        received_for: Array[String],
        html: String?,
        text: String?,
        headers: Hash[String, String]?,
        message_id: String,
        raw?: {
          download_url: String,
          expires_at: String,
        }?,
        attachments: Array[inbound_attachment],
      }

      type list_receiving_email = {
        id: String,
        to: Array[String],
        from: String,
        created_at: String,
        subject: String,
        bcc: Array[String],
        cc: Array[String],
        reply_to: Array[String],
        received_for: Array[String],
        message_id: String,
        attachments: Array[inbound_attachment],
      }

      type list_receiving_emails_response = {
        object: "list",
        has_more: bool,
        data: Array[list_receiving_email],
      }

      def self.get: (String email_id, ?Hash[Symbol, untyped] params) -> (Resend::Response & get_receiving_email_response)
      def self.list: (?limit: Integer?, ?after: String?, ?before: String?) -> (Resend::Response & list_receiving_emails_response)
    end
  end
end
